### ISSUE TITLE
error running qpbayes

### ISSUE THREAD

**Issue by gargkritika** [ekirving/qpbrute#16]
Hi Ervin

I have installed qpbrute using conda. I am able to run the first step, however, I get the following error when I run the qpBayes script. I am not sure which R package maybe an issue here.

Thank you very much.

Best regards
Kritika

INFO: There are 98 graphs to compute Bayes factors for.
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/qpbrute/qpbayes.py", line 212, in model_likelihood
    run_cmd(
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/qpbrute/utils.py", line 67, in run_cmd
    raise RuntimeError(f"ERROR: '{err}'; RETCODE:{proc.returncode}\n" + " ".join(cmd))
RuntimeError: ERROR: 'b'Error: package \xe2\x80\x98adaptivetau\xe2\x80\x99 could not be loaded\nExecution halted\n''; RETCODE:1
Rscript /home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/qpbrute/rscript/model_likelihood.R internal_subset_3 fb088b7e76d6 internal_subset_3/dstats/internal_subset_3.csv 2 5 2000000 1100000
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/balaji/anaconda3/envs/qpbrute_new/bin/qpBayes", line 8, in <module>
    sys.exit(qpbayes())
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/qpbrute/qpbayes.py", line 372, in qpbayes
    calculate_bayes_factors(
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/qpbrute/qpbayes.py", line 291, in calculate_bayes_factors
    qpb.calculate_bayes_factors()
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/qpbrute/qpbayes.py", line 196, in calculate_bayes_factors
    pool.map(self.model_likelihood, self.graphs)
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/multiprocess/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/multiprocess/pool.py", line 771, in get
    raise self._value
RuntimeError: ERROR: 'b'Error: package \xe2\x80\x98adaptivetau\xe2\x80\x99 could not be loaded\nExecution halted\n''; RETCODE:1
Rscript /home/balaji/anaconda3/envs/qpbrute_new/lib/python3.8/site-packages/qpbrute/rscript/model_likelihood.R internal_subset_3 fb088b7e76d6 internal_subset_3/dstats/internal_subset_3.csv 2 5 2000000 1100000

**Comment by ekirving** [comment]
Hi Kritika,

Sorry to hear that you've had some installation troubles with `qpBrute`

I've seen this error before, and it indicates that the `R` package dependencies were not properly installed (this happens sometimes with `conda` installations and I have yet to discover the cause).

The solution is to manually re-install the problematic package:

```
# activate your conda environment
conda activate qpbrute

# open an R session
R

# reinstall the package that will not load
install.packages("adaptivetau")
```

Then try running `qpBayes` again.

Cheers,
Evan
