### ISSUE TITLE
issues with running qpbrute

### ISSUE THREAD

**Issue by gargkritika** [ekirving/qpbrute#21]
Hi Ervin
I am running qpbrute with a new dataset. I installed qpbrute using conda. I am getting the following error

INFO: There are 5,040 possible starting orders for the given nodes.
INFO: Performing an exhaustive search.
INFO: Starting list ['A_magna', 'A_graeca', 'A_chukar', 'A_barbara', 'A_rufa', 'A_philbyi', 'A_melanocephala']
Traceback (most recent call last):
  File "/home/kritika/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbrute.py", line 318, in run_qpgraph
    with open(log_file, "r") as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'alectoris_subset_1/graphs/alectoris_subset_1-96916fd2f7c6.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kritika/anaconda3/envs/qpbrute/bin/qpBrute", line 8, in <module>
    sys.exit(qpbrute())
  File "/home/kritika/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbrute.py", line 905, in qpbrute
    permute_qpgraph(
  File "/home/kritika/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbrute.py", line 814, in permute_qpgraph
    pq.find_graph()
  File "/home/kritika/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbrute.py", line 718, in find_graph
    self.recurse_tree(root_tree, self.nodes[1], self.nodes[2:])
  File "/home/kritika/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbrute.py", line 120, in recurse_tree
    results = self.test_trees(new_trees, depth)
  File "/home/kritika/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbrute.py", line 213, in test_trees
    result = self.run_qpgraph((new_tree, depth))
  File "/home/kritika/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbrute.py", line 335, in run_qpgraph
    log = run_cmd(
  File "/home/kritika/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/utils.py", line 67, in run_cmd
    raise RuntimeError(f"ERROR: '{err}'; RETCODE:{proc.returncode}\n" + " ".join(cmd))
RuntimeError: ERROR: 'b'fatalx:\n(genotypes) bad ID (SNP): SNP:#    1    0.0    16185    G    A\n\n''; RETCODE:-6
qpGraph -p alectoris.par -g alectoris_subset_1/graphs/alectoris_subset_1-96916fd2f7c6.graph -d alectoris_subset_1/graphs/alectoris_subset_1-96916fd2f7c6.dot

The log files are not being generated. I have edited the SNP file as per the example input file and the test example file runs correctly on the system. 

Please suggest a possible solution for this error. If you need any of the input files, I can email them to you. 

Thank you
Best regards
Kritika

**Comment by ekirving** [comment]
Hi Kritika,

Your error message indicates that the genotype file is malformed. 

How did you create this file? Your messages says you "edited the SNP file" which should not be necessary. 

The input files should be generated using the `convertf` software from the `EIGENSTRAT` package https://github.com/DReichLab/EIG/blob/master/CONVERTF/README

Best wishes,
Evan
