### ISSUE TITLE
qpBayes cannot load the package adaptivetau

### ISSUE THREAD

**Issue by DONG-Wenjie** [ekirving/qpbrute#23]
Hello, I encountered the following error when running qpBayes. I installed qpBrute in a virtual environment using conda, following the steps provided on this GitHub page. The software seems to indicate that the R package adaptivetau cannot be loaded, but the package is already installed in the environment. Has anyone experienced the same error? What is the problem with it and how could I fix it?

The error messages are as follows:
"
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbayes.py", line 212, in model_likelihood
    run_cmd(
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/utils.py", line 67, in run_cmd
    raise RuntimeError(f"ERROR: '{err}'; RETCODE:{proc.returncode}\n" + " ".join(cmd))
RuntimeError: ERROR: 'b'Error: package \xe2\x80\x98adaptivetau\xe2\x80\x99 could not be loaded\nExecution halted\n''; RETCODE:1
Rscript /gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/rscript/model_likelihood.R qpbrute_sim4pop_1 5e30802d1fde qpbrute_sim4pop_1/dstats/qpbrute_sim4pop_1.csv 2 5 2000000 1100000
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/bin/qpBayes", line 8, in <module>
    sys.exit(qpbayes())
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbayes.py", line 372, in qpbayes
    calculate_bayes_factors(
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbayes.py", line 291, in calculate_bayes_factors
    qpb.calculate_bayes_factors()
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/qpbayes.py", line 196, in calculate_bayes_factors
    pool.map(self.model_likelihood, self.graphs)
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/multiprocess/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/multiprocess/pool.py", line 771, in get
    raise self._value
RuntimeError: ERROR: 'b'Error: package \xe2\x80\x98adaptivetau\xe2\x80\x99 could not be loaded\nExecution halted\n''; RETCODE:1
Rscript /gpfs/home/dongwj/anaconda3/envs/qpbrute/lib/python3.8/site-packages/qpbrute/rscript/model_likelihood.R qpbrute_sim4pop_1 5e30802d1fde qpbrute_sim4pop_1/dstats/qpbrute_sim4pop_1.csv 2 5 2000000 1100000
“

Thanks a lot!!

Dong

**Comment by ekirving** [comment]
Hi Dong,

Try activating your conda environment and manually reinstalling the `adaptivetau` R package.

Cheers,
Evan

**Comment by DONG-Wenjie** [comment]
> Hi Dong,
> 
> Try activating your conda environment and manually reinstalling the `adaptivetau` R package.
> 
> Cheers, Evan

Great! The program seems to work fine after I manually installed a newer version of adaptivetau package. Thank you very much!!
